doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7.31'
                charset: utf8mb4
                
            divaltoreel:
                # configure these for your database server
                url: '%env(resolve:DATABASE_DIVALTO_REEL_URL)%'
                driver: 'sqlsrv'
                charset: UTF-8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            divaltoreel:
                connection: divaltoreel
                mappings:
                    divaltoreel:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Divalto'
                        prefix: 'App\Entity\Divalto'
                        alias: divaltoreel

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
