# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            DivaltoSvg:
                # configure these for your database server
                url: '%env(resolve:DATABASE_DIVALTO_SVG_URL)%'
                driver: 'sqlsrv'
                server_version: '5.7'
                charset: utf8mb4
            DivaltoReel:
                # configure these for your database server
                url: '%env(resolve:DATABASE_DIVALTO_REEL_URL)%'
                driver: 'sqlsrv'
                #server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            DivaltoSvg:
                connection: DivaltoSvg
                mappings:
                    DivaltoSvg:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/DivaltoSvg'
                        prefix: 'App\Entity\DivaltoSvg'
                        alias: DivaltoSvg
            DivaltoReel:
                connection: DivaltoReel
                mappings:
                    DivaltoReel:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/DivaltoReel'
                        prefix: 'App\Entity\DivaltoReel'
                        alias: DivaltoReel
