controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

afficher_fichier:
    path: /fichiers/{chemin}
    controller: App\Controller\FichierController::afficherFichier


