controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

execute_command:
    path: /execute-command
    controller: App\Controller\ExecuteCommandController::executeCommand




