# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/doc/Roby/Fsc'
    doc_lhermitte: '%kernel.project_dir%/public/doc/Lhermitte_freres'
    doc_lhermitte_affaires: '%kernel.project_dir%/public/doc/Lhermitte_freres/Affaires'
    doc_roby: '%kernel.project_dir%/public/doc/Roby'
    doc: '%kernel.project_dir%/public/doc'
    doc_axis: '%kernel.project_dir%/public/doc/Axis'
    doc_francial: '%kernel.project_dir%/public/doc/Francial'
    doc_tickets: '%kernel.project_dir%/public/doc/tickets'
    doc_profiles: '%kernel.project_dir%/public/img/profile'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\TrackingsListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request' }